version: '3.7'

networks:
    terracotta-net:
        driver: overlay
        external: false
        name: terracotta-net

services:
    app1:
        image: cache.app
        build:
            context: ./app
        depends_on:
            - storage
            - terracotta-1
        environment:
            port: 8081
            args: data.host=storage,data.port=8880,cache.node.host=terracotta-1,cache.node.port=9410,app.nodes.ports=8081:8082:8083
        ports:
            - 8081:8081
        networks:
            - terracotta-net

    app2:
        image: cache.app
        build:
            context: ./app
        depends_on:
            - storage
            - terracotta-1
        environment:
            port: 8082
            args: data.host=storage,data.port=8880,cache.node.host=terracotta-2,cache.node.port=9410,app.nodes.ports=8081:8082:8083
        ports:
            - 8082:8082
        networks:
            - terracotta-net

    app3:
        image: cache.app
        build:
            context: ./app
        depends_on:
            - storage
            - terracotta-2
        environment:
            port: 8083
            args: data.host=storage,data.port=8880,cache.node.host=terracotta-2,cache.node.port=9410,app.nodes.ports=8081:8082:8083
        ports:
            - 8083:8083
        networks:
            - terracotta-net

    storage:
        image: cache.storage
        build:
            context: ./storage
        environment:
            port: 8880
            response_delay: 2000
        ports:
            - 8880:8880
        networks:
            - terracotta-net

    terracotta-1:
        hostname: terracotta-1
        image: terracotta/terracotta-server-oss:5.6.4
        environment:
            - TC_SERVER1=terracotta-1
            - TC_SERVER2=terracotta-2
        networks:
            - terracotta-net

    terracotta-2:
        hostname: terracotta-2
        image: terracotta/terracotta-server-oss:5.6.4
        environment:
            - TC_SERVER1=terracotta-1
            - TC_SERVER2=terracotta-2
        networks:
            - terracotta-net
